spring:
  datasource:
    url: jdbc:mariadb://27.102.205.66:3306/jpa_test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: pluxity123!@#

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

logging:
  level:
    "[org.hibernate]": ERROR





